#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/escradesk/escradesk /usr/bin/escradesk
	
	if [ "systemd" == "$INITSYS" ]; then

		rm -f /etc/systemd/system/escradesk.service /usr/lib/systemd/system/escradesk.service /usr/lib/systemd/user/escradesk.service >/dev/null 2>&1 || true
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/escradesk/files/systemd/escradesk.service /usr/lib/systemd/system/escradesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/escradesk.service
		fi
		systemctl daemon-reload
		systemctl enable escradesk
		systemctl start escradesk
	fi
fi
