#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		rm -f /usr/bin/rustdesk
		
		if [ "systemd" == "${INITSYS}" ]; then
			rm -f /usr/bin/escradesk

			systemctl stop escradesk || true
			systemctl disable escradesk || true
			rm -f /etc/systemd/system/escradesk.service /usr/lib/systemd/system/escradesk.service || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'escradesk +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop escradesk >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/escradesk.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
